// genopcodes generates internal/protocol/opcodes_gen.go from the original
// Java properties files (recv.properties / send.properties of ZEVMS 079MAX2).
//
// Java reference: handling/ExternalCodeTableGetter.java
//   value := props[name]; format "0x13" | "123" | "OTHERKEY 0x04"(base+offset)
//
// Usage: go run ./tools/genopcodes -src I:\Zevms\src\main\java\properties
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type opcode struct {
	Name  string
	Value uint16
}

func main() {
	src := flag.String("src", `I:\Zevms\src\main\java\properties`, "dir containing recv.properties / send.properties")
	out := flag.String("out", `I:\GMS\internal\protocol\opcodes_gen.go`, "output .go file")
	flag.Parse()

	recv, err := parseProps(filepath.Join(*src, "recv.properties"))
	if err != nil {
		log.Fatalf("recv: %v", err)
	}
	send, err := parseProps(filepath.Join(*src, "send.properties"))
	if err != nil {
		log.Fatalf("send: %v", err)
	}
	// resolve "NAME offset" compound values now that all names are known
	resolveCompound(recv)
	resolveCompound(send)

	if err := emit(*out, recv, send); err != nil {
		log.Fatalf("emit: %v", err)
	}
	fmt.Printf("recv=%d send=%d -> %s\n", len(recv), len(send), *out)
}

// parseProps follows java.util.Properties semantics: '#'/'!' comments,
// '=' or ':' separators (with optional whitespace), later entries win.
func parseProps(path string) ([]opcode, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	seen := map[string]uint16{}
	var order []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "!") {
			continue
		}
		var key, val string
		if i := strings.IndexAny(line, "=:"); i >= 0 {
			key = strings.TrimSpace(line[:i])
			val = strings.TrimSpace(line[i+1:])
		} else {
			key = line
		}
		if key == "" {
			continue
		}
		if _, dup := seen[key]; !dup {
			order = append(order, key)
		}
		seen[key] = 0 // raw value parsed later; store placeholder to keep order
		// keep raw string for compound resolution
		raw[key] = val
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}

	var out []opcode
	for _, k := range order {
		v, err := evalValue(k, seen)
		if err != nil {
			// Java silently defaults missing to -2; keep faithful but visible
			log.Printf("warn: %s: %v (skipping)", k, err)
			continue
		}
		out = append(out, opcode{Name: k, Value: v})
	}
	return out, nil
}

// raw holds unparsed values during compound resolution.
var raw = map[string]string{}

func evalValue(key string, seen map[string]uint16) (uint16, error) {
	val, ok := raw[key]
	if !ok || val == "" {
		return 0, fmt.Errorf("no value")
	}
	parts := strings.Fields(val)
	var base uint16
	offsetStr := parts[0]
	if len(parts) == 2 {
		// "OTHERKEY 0x04" -> base from other opcode + offset
		other, err := evalValue(parts[0], seen)
		if err != nil {
			return 0, fmt.Errorf("compound base %q: %w", parts[0], err)
		}
		base = other
		offsetStr = parts[1]
	}
	var off uint16
	if strings.HasPrefix(offsetStr, "0x") || strings.HasPrefix(offsetStr, "0X") {
		n, err := strconv.ParseUint(offsetStr[2:], 16, 32)
		if err != nil {
			return 0, err
		}
		off = uint16(n)
	} else {
		n, err := strconv.ParseUint(offsetStr, 10, 32)
		if err != nil {
			return 0, err
		}
		off = uint16(n)
	}
	return base + off, nil
}

func resolveCompound(ops []opcode) {
	// already resolved in evalValue via recursion; nothing to do
}

func emit(path string, recv, send []opcode) error {
	sort.Slice(recv, func(i, j int) bool { return recv[i].Name < recv[j].Name })
	sort.Slice(send, func(i, j int) bool { return send[i].Name < send[j].Name })

	var b strings.Builder
	b.WriteString("// Code generated by tools/genopcodes from ZEVMS recv/send.properties. DO NOT EDIT.\n")
	b.WriteString("// Java source: handling/RecvPacketOpcode.java / SendPacketOpcode.java + properties.\n\n")
	b.WriteString("package protocol\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString("// RecvOp is a client->server packet opcode (155 in original 079MAX2).\n")
	b.WriteString("type RecvOp uint16\n\n")
	writeConsts(&b, "RecvOp", "Recv", recv)
	b.WriteString("\n// SendOp is a server->client packet opcode (245 in original 079MAX2).\n")
	b.WriteString("type SendOp uint16\n\n")
	writeConsts(&b, "SendOp", "Send", send)

	b.WriteString("\n// recvNames/sendNames support opcode->name lookup for logging/debug.\n")
	b.WriteString("// NOTE: disabled opcodes share the 0xFF placeholder value in the original\n")
	b.WriteString("// properties; only the first name (sorted) maps for those - use ByName for exact.\n")
	b.WriteString("var recvNames = map[RecvOp]string{\n")
	usedRecv := map[uint16]bool{}
	for _, o := range recv {
		if usedRecv[o.Value] {
			continue
		}
		usedRecv[o.Value] = true
		fmt.Fprintf(&b, "\tRecv%s: %q,\n", exportName(o.Name), o.Name)
	}
	b.WriteString("}\n\n")
	b.WriteString("var sendNames = map[SendOp]string{\n")
	usedSend := map[uint16]bool{}
	for _, o := range send {
		if usedSend[o.Value] {
			continue
		}
		usedSend[o.Value] = true
		fmt.Fprintf(&b, "\tSend%s: %q,\n", exportName(o.Name), o.Name)
	}
	b.WriteString("}\n\n")

	b.WriteString("// recvByNames/sendByNames: exact name->opcode (all keys, including shared-value).\n")
	b.WriteString("var recvByNames = map[string]RecvOp{\n")
	for _, o := range recv {
		fmt.Fprintf(&b, "\t%q: Recv%s,\n", o.Name, exportName(o.Name))
	}
	b.WriteString("}\n\n")
	b.WriteString("var sendByNames = map[string]SendOp{\n")
	for _, o := range send {
		fmt.Fprintf(&b, "\t%q: Send%s,\n", o.Name, exportName(o.Name))
	}
	b.WriteString("}\n")

	b.WriteString(`
// Name returns the canonical name for a recv opcode ("" if unknown).
func (o RecvOp) Name() string { return recvNames[o] }

// Name returns the canonical name for a send opcode ("" if unknown).
func (o SendOp) Name() string { return sendNames[o] }

// String implements fmt.Stringer.
func (o RecvOp) String() string { return nameOrHex(o, o.Name()) }

// String implements fmt.Stringer.
func (o SendOp) String() string { return nameOrHex(o, o.Name()) }

func nameOrHex[T ~uint16](v T, name string) string {
	if name == "" {
		return fmt.Sprintf("0x%04X", uint16(v))
	}
	return name
}

// RecvByName / SendByName reverse lookups from name (used by config override loader).
func RecvByName(name string) (RecvOp, bool) {
	op, ok := recvByNames[name]
	return op, ok
}

func SendByName(name string) (SendOp, bool) {
	op, ok := sendByNames[name]
	return op, ok
}
`)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeConsts(b *strings.Builder, typeName, prefix string, ops []opcode) {
	b.WriteString("const (\n")
	for _, o := range ops {
		fmt.Fprintf(b, "\t%s%s %s = 0x%04X\n", prefix, exportName(o.Name), typeName, o.Value)
	}
	b.WriteString(")\n\n")
}

// exportName turns UPPER_SNAKE Java enum names into Go-style first letter safety.
// Names are already valid Go identifiers (letters/digits/_), keep as-is.
func exportName(name string) string {
	return name
}
