package dropgen

import (
	"fmt"
	"io"
	"strings"
)

// WriteSQL renders the generated rows as a portable SQL script (the Go
// equivalent of MonsterDropCreator's mobDrop.sql).
//
// Notes:
//   - one INSERT per monster, exactly like the Java writer;
//   - explicit column list instead of Java's positional "VALUES (DEFAULT, …)"
//     so the script survives column additions;
//   - the monster-card rows are emitted as comments: the 079MAX2 database has
//     no monstercarddata table (checked against the live schema), so
//     executing them would fail. They stay visible for reference.
func WriteSQL(w io.Writer, r *Result, table string) error {
	if table == "" {
		table = "drop_data"
	}
	var b strings.Builder
	b.WriteString("-- wz-derived drop table, generated by tools/wztosql (GMS-P3.5)\n")
	b.WriteString("--\n")
	b.WriteString("-- WARNING: the live 079MAX2 drop_data is hand-tuned and is the\n")
	b.WriteString("-- source of truth. This file is a rebuild for comparison only -\n")
	b.WriteString("-- importing it over a populated drop_data would destroy tuning.\n")
	b.WriteString("--\n")
	fmt.Fprintf(&b, "-- %s\n\n", r.Summary())

	head := fmt.Sprintf("INSERT INTO `%s` "+
		"(`dropperid`, `itemid`, `minimum_quantity`, `maximum_quantity`, `questid`, `chance`) VALUES\n", table)

	r.SortEntries()
	i := 0
	for i < len(r.Entries) {
		mob := r.Entries[i].MonsterID
		b.WriteString(head)
		first := true
		for i < len(r.Entries) && r.Entries[i].MonsterID == mob {
			e := r.Entries[i]
			if !first {
				b.WriteString(",\n")
			}
			first = false
			fmt.Fprintf(&b, "(%d, %d, %d, %d, %d, %d)",
				e.MonsterID, e.ItemID, e.Minimum, e.Maximum, e.QuestID, e.Chance)
			if e.Note != "" {
				fmt.Fprintf(&b, " -- %s", oneLine(e.Note))
			}
			i++
		}
		b.WriteString(";\n\n")
	}

	if len(r.Cards) > 0 {
		b.WriteString("-- monstercarddata (Java emitted this table; the 079MAX2 database\n")
		b.WriteString("-- has no such table, so it is commented out):\n")
		for _, c := range r.Cards {
			fmt.Fprintf(&b, "-- (%d, %d, %d)\n", c.Seq, c.CardID, c.MonsterID)
		}
		b.WriteString("\n")
	}

	if len(r.Errors) > 0 {
		b.WriteString("-- warnings during generation:\n")
		for _, e := range r.Errors {
			fmt.Fprintf(&b, "-- %s\n", oneLine(e))
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// oneLine keeps a note inside a single-line SQL comment.
func oneLine(s string) string {
	s = strings.NewReplacer("\r", " ", "\n", " ", "*/", " ").Replace(s)
	return strings.TrimSpace(s)
}
